# Generated by Django 5.1.4 on 2025-01-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_usera_alter_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usera',
            new_name='user',
        ),
    ]
